include:
  - local: '/.developer-vars.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/.huihui-ops-vars.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/maven-huihui.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/sonar.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/docker-image.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/inside-deploy-java.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/uat-deploy-java.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/prod-deploy-java.yml'


variables:
  # image group, sre define
  REGISTRY_GROUP: '$BUSINESS_NAME'
  # image name, sre define
  REGISTRY_IMAGE: '${APP_NAME}:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}'
  # k8s config, sre define
  KUBECONFIG: '/config'
  # k8s deployments, sre define
  CD_REPO: 'gitlab.leke.cn/deployments/${BUSINESS_NAME}/backend/${APP_NAME}.git'


stages:
  - maven package
  - build docker image
  - deploy to dev
  - deploy to testing
  - deploy to pre
  - deploy to prod


Maven build:
  stage: maven package
  tags:
    - k8s
  extends: .maven-build
  script:
    - mvn -DskipTests clean package -P !dev $MAVEN_OPTS


SonarQube check:
  stage: maven package
  extends: .sonarqube-check


Image build:
  stage: build docker image
  extends: .docker


dev-169:
  stage: deploy to dev
  variables:
    # sre and developer define
    ENV_NAME: 'dev-169'
    # sre define
    APP_CONFIG: '${JVM_OPTS_DEV169}'
    # sre define
    ARGO_PROJ: '${BUSINESS_NAME}-dev'
    # sre define
    CD_GIT_PATH: 'dev'
    DNS: '$DNS_DEV169'
  extends: .deploy
  only:
    - master


testing-1:
  stage: deploy to testing
  variables:
    ENV_NAME: 'testing-1'
    APP_CONFIG: '${JVM_OPTS_TEST1}'
    ARGO_PROJ: '${BUSINESS_NAME}-dev'
    CD_GIT_PATH: 'testing'
    DNS: '$DNS_TESTING1'
  extends: .deploy
  only:
    - /^testing-1-.*/
    - /^hotfix-.*/
    - master


testing-2:
  stage: deploy to testing
  variables:
    ENV_NAME: 'testing-2'
    APP_CONFIG: '${JVM_OPTS_TESTING2}'
    ARGO_PROJ: '${BUSINESS_NAME}-dev'
    CD_GIT_PATH: 'testing'
    DNS: '$DNS_TESTING2'
  extends: .deploy
  only:
    - /^testing-2-.*/
    - /^hotfix-.*/
    - master


testing-3:
  stage: deploy to testing
  variables:
    ENV_NAME: 'testing-3'
    APP_CONFIG: '${JVM_OPTS_TESTING3}'
    ARGO_PROJ: '${BUSINESS_NAME}-dev'
    CD_GIT_PATH: 'testing'
    DNS: '$DNS_TESTING3'
  extends: .deploy
  only:
    - /^testing-3-.*/
    - /^hotfix-.*/
    - master


pre:
  stage: deploy to pre
  variables:
    ENV_NAME: 'pre'
    APP_CONFIG: '${JVM_OPTS_PRE}'
    ARGO_PROJ: '${BUSINESS_NAME}-pre'
    DNS: '$DNS_PRE'
  extends: .prod-deploy
  only:
    - release
    - /^hotfix-.*/


prod:
  stage: deploy to prod
  variables:
    APP_CONFIG: '${JVM_OPTS_PROD}'
    ARGO_PROJ: '${BUSINESS_NAME}-prod'
    DNS: '$DNS_PROD'
  extends: .prod-deploy
  only:
    - release
    - /^hotfix-.*/

