include:
  - local: '/.developer-vars.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/.huihui-ops-vars.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/maven-huihui-color.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/sonar-huihui.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/docker-image-color.yml'
  - remote: 'https://gitlab.leke.cn/deployments/include/-/raw/master/huihui-jar-deploy-v2-color.yml'


variables:
  # image group, sre define
  REGISTRY_GROUP: '$BUSINESS_NAME'
  # image name, sre define
  REGISTRY_IMAGE_JAR: '${APP_NAME}:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}'
  # image name, sre define
  REGISTRY_IMAGE: '${APP_NAME}:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}'
  # k8s config, sre define
  KUBECONFIG: '/config'
  # k8s deployments, sre define
  CD_REPO: 'gitlab.leke.cn/deployments/${BUSINESS_NAME}/backend/${APP_NAME}.git'
  # GM Image, by include '.huihui-ops-vars.yml'
  REGISTRY_IMAGE_JAVA: '${REGISTRY_IMAGE_JAVA_GM}'


stages:
  - maven package
  - build docker image
  - deploy to dev
  - deploy to testing
  - deploy to prod


Maven build:
  stage: maven package
  tags:
    - k8s
  extends: .maven-build
  script:
    - mvn -DskipTests clean install -U -Pproduct $MAVEN_OPTS


#SonarQube check:
#  stage: maven package
#  extends: .sonarqube-check
#
#
Image build:
  stage: build docker image
  extends: .docker
  needs: ["Maven build"]

dev:
  stage: deploy to dev
  variables:
    K8S_CLUSTER: '$INSIDE_K8S_CLUSTER'
    ENV_NAME: 'dev-${v}'
    CD_GIT_BRANCH: 'dev-${v}'
    K8S_NS: '${BUSINESS_NAME}-testing-1'
    APP_CONFIG: '${JVM_OPTS_TESTING1}'
    ARGO_PROJ: '${BUSINESS_NAME}-dev'
    CD_GIT_PATH: 'testing'
    DNS: '$DNS_TESTING1'
    # nacos
    NACOS_IP: '$NACOS_IP_TESTING1'
    NACOS_NS: '$NACOS_NS_TESTING1'
  extends: .deploy
  only:
    - /^testing-1-.*/


testing:
  stage: deploy to testing
  variables:
    K8S_CLUSTER: '$CCE1_DEV'
    ENV_NAME: 'testing-${v}'
    CD_GIT_BRANCH: 'testing-${v}'
    K8S_NS: '${BUSINESS_NAME}-testing-4'
    APP_CONFIG: '${JVM_OPTS_TESTING4}'
    ARGO_PROJ: '${BUSINESS_NAME}-dev'
    CD_GIT_PATH: 'testing-cce1'
    DNS: '$DNS_TESTING4'
    # nacos
    NACOS_IP: '$NACOS_IP_TESTING4'
    NACOS_NS: '$NACOS_NS_TESTING4'
  extends: .deploy
  needs: ["Image build"]
  only:
    - /^testing-4-.*/
    - release


prod:
  stage: deploy to prod
  variables:
    K8S_CLUSTER: '$CCE2'
    ENV_NAME: 'prod-${v}'
    CD_GIT_BRANCH: 'prod-${v}'
    K8S_NS: '${BUSINESS_NAME}-prod'
    APP_CONFIG: '${JVM_OPTS_PROD}'
    ARGO_PROJ: '${BUSINESS_NAME}-prod'
    CD_GIT_PATH: 'prod'
    DNS: '$DNS_PROD'
    # nacos
    NACOS_IP: '$NACOS_IP_PROD'
    NACOS_NS: '$NACOS_NS_PROD_V2'
  extends: .deploy
  needs: ["Image build"]
  only:
    - /^release.*/
    - /^hotfix-.*/
