spring:
  application:
    name: health-mall-product
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql:replication://192.168.21.215:3306/mall_product?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: strongEhp
    password: WgqciKVG
  redis:
    host: 192.168.21.202
    port: 6379
    password: KJO!laNrYw0AjHYF    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
    database: 7
  cloud:
    inetutils:
      preferredNetworks: [ '192.168' ]
    nacos:
      config:
        server-addr: 192.168.21.202:8848 #nacos注册中心地址
        group: ${spring.application.name} #分组ID，这里使用spring.application.name的值
        file-extension: properties
        refresh-enabled: true
        shared-configs:
          - data-id: config.properties # 通用配置
            group: ${spring.cloud.nacos.config.group}
            refresh: true
          - data-id: cache.properties # 缓存配置
            group: ${spring.cloud.nacos.config.group}
            refresh: false
          - data-id: mq.properties # MQ配置
            group: ${spring.cloud.nacos.config.group}
            refresh: false
          - data-id: db.properties # 数据库配置
            group: ${spring.cloud.nacos.config.group}
            refresh: false
          - data-id: log4j2-spring.xml # log4j2配置
            group: ${spring.cloud.nacos.config.group}
            refresh: true
        enabled: false
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        service: ${spring.application.name}

  #因为Feign调用默认的超时时间为一分钟，一分钟接口不能返回就会抛出异常
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include:
          - "prometheus"
          - "health"
        exclude:
          - "solr"
          - "elasticsearch"
  metrics:
    tags:
      application: ${spring.application.name}

strong:
  swagger:
    enable: true
    base-package: com.drstrong.health.product
    title: 商品模块接口文档
    description: 茴茴健康商城,商品模块接口文档
    url: http://localhost:9092/doc.html

rocketmq:
  name-server: 192.168.21.202:9876
  producer:
    group: gid_health_mall_product_producer_tes
