spring:
  datasource:
    url: jdbc:mysql:replication://192.168.21.3:3306/mall_product?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: strongEhp
    password: WgqciKVG